### ISSUE TITLE
Enhance Base64 Encoder to receive zero bytes

### ISSUE THREAD

**Issue by Mikumiku747** [Mikumiku747/lqip#17]
https://github.com/Mikumiku747/lqip/blob/ff449fbb9956b0eb776bb28f88c3934caa235469/base64.c#L86

Currently, the Base64 encoder looks for a NULL character to mark the end of the string, but since the image data is likely to involve zeroes, this will mess with it and it's likely the Encoder will think it's reached the end of the string when really it's just reached a zero byte. Hence, it needs to be changed so that it finds the end of the string based on a given length, not a zero byte marking the end. Let me know if you have any questions. 
 - Daniel

**Comment by zouhir** [comment]
in progress!
